### ISSUE TITLE
`bun install` が確率的に失敗する

### ISSUE THREAD

**Issue by r4ai** [shuiro-dev/shuiro#174]
`bun install`時に次のようなエラーが発生し、CIが確率的に失敗している

```plaintext
Run bun install --frozen-lockfile
bun install v1.1.34 (5e5e7c60)
Resolving dependencies
Resolved, downloaded and extracted [46]
Error: ENOENT: no such file or directory, stat '/home/runner/work/shuiro/shuiro/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node'
error: "prisma" exited with code 1
12 | export default "unknown";
                    ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "Error: ENOENT: no such file or directory, stat '/home/runner/work/shuiro/shuiro/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node'\nerror: \"prisma\" exited with code 1\n",
  "stdout": ""
}

      at new ShellError (unknown:12:16)
      at new ShellPromise (unknown:72:16)
      at BunShell (unknown:1[8](https://github.com/shuiro-dev/shuiro/actions/runs/11641207622/job/32419439551#step:4:9)7:35)
      at /home/runner/work/shuiro/shuiro/backend/src/bin/postinstall.ts:35:[9](https://github.com/shuiro-dev/shuiro/actions/runs/11641207622/job/32419439551#step:4:10)
      at generatePrismaClient (/home/runner/work/shuiro/shuiro/backend/src/bin/postinstall.ts:34:30)
      at module code (/home/runner/work/shuiro/shuiro/backend/src/bin/postinstall.ts:40:7)
      at unknown:2:1

Bun v1.1.34 (Linux x64 baseline)

error: postinstall script from "backend" exited with 1
Error: Process completed with exit code 1.
```

<details>
<summary>エラーログ（全体）</summary>

```plaintxt
2024-11-02T08:17:26.8210240Z Current runner version: '2.320.0'
2024-11-02T08:17:26.8337665Z ##[group]Operating System
2024-11-02T08:17:26.8338745Z Ubuntu
2024-11-02T08:17:26.8339063Z 24.04.1
2024-11-02T08:17:26.8339299Z LTS
2024-11-02T08:17:26.8339545Z ##[endgroup]
2024-11-02T08:17:26.8339834Z ##[group]Runner Image
2024-11-02T08:17:26.8340174Z Image: ubuntu-24.04
2024-11-02T08:17:26.8340484Z Version: 20241016.1.0
2024-11-02T08:17:26.8341390Z Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20241016.1/images/ubuntu/Ubuntu2404-Readme.md
2024-11-02T08:17:26.8342724Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20241016.1
2024-11-02T08:17:26.8343493Z ##[endgroup]
2024-11-02T08:17:26.8343790Z ##[group]Runner Image Provisioner
2024-11-02T08:17:26.8344174Z 2.0.384.1
2024-11-02T08:17:26.8344416Z ##[endgroup]
2024-11-02T08:17:26.8360120Z ##[group]GITHUB_TOKEN Permissions
2024-11-02T08:17:26.8361591Z Contents: read
2024-11-02T08:17:26.8361911Z Metadata: read
2024-11-02T08:17:26.8362322Z Packages: read
2024-11-02T08:17:26.8362623Z ##[endgroup]
2024-11-02T08:17:26.8365511Z Secret source: Actions
2024-11-02T08:17:26.8365983Z Prepare workflow directory
2024-11-02T08:17:26.9128278Z Prepare all required actions
2024-11-02T08:17:26.9289309Z Getting action download info
2024-11-02T08:17:27.1593203Z Download action repository 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
2024-11-02T08:17:27.7454016Z Download action repository 'jdx/mise-action@a4cfebde9ceb9b49b54db1d148fa86a52e1b7fab' (SHA:a4cfebde9ceb9b49b54db1d148fa86a52e1b7fab)
2024-11-02T08:17:28.3745967Z Complete job name: Lint
2024-11-02T08:17:28.4619581Z ##[group]Run actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
2024-11-02T08:17:28.4620299Z with:
2024-11-02T08:17:28.4620599Z   repository: shuiro-dev/shuiro
2024-11-02T08:17:28.4621203Z   token: ***
2024-11-02T08:17:28.4621492Z   ssh-strict: true
2024-11-02T08:17:28.4621785Z   ssh-user: git
2024-11-02T08:17:28.4622105Z   persist-credentials: true
2024-11-02T08:17:28.4622490Z   clean: true
2024-11-02T08:17:28.4622914Z   sparse-checkout-cone-mode: true
2024-11-02T08:17:28.4623349Z   fetch-depth: 1
2024-11-02T08:17:28.4623645Z   fetch-tags: false
2024-11-02T08:17:28.4623959Z   show-progress: true
2024-11-02T08:17:28.4624273Z   lfs: false
2024-11-02T08:17:28.4624562Z   submodules: false
2024-11-02T08:17:28.4624874Z   set-safe-directory: true
2024-11-02T08:17:28.4625229Z ##[endgroup]
2024-11-02T08:17:28.7151265Z Syncing repository: shuiro-dev/shuiro
2024-11-02T08:17:28.7153502Z ##[group]Getting Git version info
2024-11-02T08:17:28.7154567Z Working directory is '/home/runner/work/shuiro/shuiro'
2024-11-02T08:17:28.7155428Z [command]/usr/bin/git version
2024-11-02T08:17:28.7214003Z git version 2.47.0
2024-11-02T08:17:28.7239337Z ##[endgroup]
2024-11-02T08:17:28.7253571Z Temporarily overriding HOME='/home/runner/work/_temp/e56157d3-6e98-41a5-94ce-361d933e2b7e' before making global git config changes
2024-11-02T08:17:28.7254788Z Adding repository directory to the temporary git global config as a safe directory
2024-11-02T08:17:28.7258915Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/shuiro/shuiro
2024-11-02T08:17:28.7294067Z Deleting the contents of '/home/runner/work/shuiro/shuiro'
2024-11-02T08:17:28.7297531Z ##[group]Initializing the repository
2024-11-02T08:17:28.7301917Z [command]/usr/bin/git init /home/runner/work/shuiro/shuiro
2024-11-02T08:17:28.7386557Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-11-02T08:17:28.7387386Z hint: is subject to change. To configure the initial branch name to use in all
2024-11-02T08:17:28.7388248Z hint: of your new repositories, which will suppress this warning, call:
2024-11-02T08:17:28.7389296Z hint:
2024-11-02T08:17:28.7389730Z hint: 	git config --global init.defaultBranch <name>
2024-11-02T08:17:28.7390272Z hint:
2024-11-02T08:17:28.7390796Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-11-02T08:17:28.7391789Z hint: 'development'. The just-created branch can be renamed via this command:
2024-11-02T08:17:28.7392495Z hint:
2024-11-02T08:17:28.7392831Z hint: 	git branch -m <name>
2024-11-02T08:17:28.7396529Z Initialized empty Git repository in /home/runner/work/shuiro/shuiro/.git/
2024-11-02T08:17:28.7406910Z [command]/usr/bin/git remote add origin https://github.com/shuiro-dev/shuiro
2024-11-02T08:17:28.7443111Z ##[endgroup]
2024-11-02T08:17:28.7443726Z ##[group]Disabling automatic garbage collection
2024-11-02T08:17:28.7447280Z [command]/usr/bin/git config --local gc.auto 0
2024-11-02T08:17:28.7476229Z ##[endgroup]
2024-11-02T08:17:28.7477272Z ##[group]Setting up auth
2024-11-02T08:17:28.7484285Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-11-02T08:17:28.7516377Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-11-02T08:17:28.7877547Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-11-02T08:17:28.7908205Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-11-02T08:17:28.8142473Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-11-02T08:17:28.8182465Z ##[endgroup]
2024-11-02T08:17:28.8183338Z ##[group]Fetching the repository
2024-11-02T08:17:28.8191276Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +9b77935d1e8e0484ead70b9385307c51690c6f5f:refs/remotes/pull/170/merge
2024-11-02T08:17:29.2496702Z From https://github.com/shuiro-dev/shuiro
2024-11-02T08:17:29.2497809Z  * [new ref]         9b77935d1e8e0484ead70b9385307c51690c6f5f -> pull/170/merge
2024-11-02T08:17:29.2524013Z ##[endgroup]
2024-11-02T08:17:29.2524715Z ##[group]Determining the checkout info
2024-11-02T08:17:29.2526631Z ##[endgroup]
2024-11-02T08:17:29.2532000Z [command]/usr/bin/git sparse-checkout disable
2024-11-02T08:17:29.2570909Z [command]/usr/bin/git config --local --unset-all extensions.worktreeConfig
2024-11-02T08:17:29.2599524Z ##[group]Checking out the ref
2024-11-02T08:17:29.2601789Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/170/merge
2024-11-02T08:17:29.2691016Z Note: switching to 'refs/remotes/pull/170/merge'.
2024-11-02T08:17:29.2691741Z 
2024-11-02T08:17:29.2692350Z You are in 'detached HEAD' state. You can look around, make experimental
2024-11-02T08:17:29.2693463Z changes and commit them, and you can discard any commits you make in this
2024-11-02T08:17:29.2694515Z state without impacting any branches by switching back to a branch.
2024-11-02T08:17:29.2695132Z 
2024-11-02T08:17:29.2695495Z If you want to create a new branch to retain commits you create, you may
2024-11-02T08:17:29.2696583Z do so (now or later) by using -c with the switch command. Example:
2024-11-02T08:17:29.2697289Z 
2024-11-02T08:17:29.2697623Z   git switch -c <new-branch-name>
2024-11-02T08:17:29.2698070Z 
2024-11-02T08:17:29.2698298Z Or undo this operation with:
2024-11-02T08:17:29.2698891Z 
2024-11-02T08:17:29.2699078Z   git switch -
2024-11-02T08:17:29.2699369Z 
2024-11-02T08:17:29.2699886Z Turn off this advice by setting config variable advice.detachedHead to false
2024-11-02T08:17:29.2700665Z 
2024-11-02T08:17:29.2701455Z HEAD is now at 9b77935 Merge cb3c373299f851caa189387cb5c60f7ff7c3a420 into 40a1afc49d9ac82c2785fd0151bf1dcee8a3d412
2024-11-02T08:17:29.2703698Z ##[endgroup]
2024-11-02T08:17:29.2739686Z [command]/usr/bin/git log -1 --format=%H
2024-11-02T08:17:29.2761841Z 9b77935d1e8e0484ead70b9385307c51690c6f5f
2024-11-02T08:17:29.3039854Z ##[group]Run jdx/mise-action@a4cfebde9ceb9b49b54db1d148fa86a52e1b7fab
2024-11-02T08:17:29.3040341Z with:
2024-11-02T08:17:29.3040561Z   install: true
2024-11-02T08:17:29.3040977Z   cache: true
2024-11-02T08:17:29.3041197Z   cache_save: true
2024-11-02T08:17:29.3041443Z   cache_key_prefix: mise-v0
2024-11-02T08:17:29.3041731Z   experimental: false
2024-11-02T08:17:29.3041976Z   log_level: info
2024-11-02T08:17:29.3042216Z ##[endgroup]
2024-11-02T08:17:29.4290830Z ##[group]Restoring mise cache
2024-11-02T08:17:31.1376767Z Received 0 of 88227043 (0.0%), 0.0 MBs/sec
2024-11-02T08:17:32.1290251Z Cache Size: ~84 MB (88227043 B)
2024-11-02T08:17:32.1327337Z [command]/usr/bin/tar -xf /home/runner/work/_temp/51916a63-05f5-440f-8ca7-3769851c95a3/cache.tzst -P -C /home/runner/work/shuiro/shuiro --use-compress-program unzstd
2024-11-02T08:17:32.1374099Z Received 88227043 of 88227043 (100.0%), 42.1 MBs/sec
2024-11-02T08:17:32.8009125Z Cache restored successfully
2024-11-02T08:17:32.8202183Z mise cache restored from key: mise-v0-linux-x64-4cf0828ab7e4d3276810d38ac7cda0e22bcf3c4f0cfd50aa5179d2f3166e02b8
2024-11-02T08:17:32.8207585Z ##[group]Setting env vars
2024-11-02T08:17:32.8208155Z Setting MISE_LOG_LEVEL=info
2024-11-02T08:17:32.8209766Z Setting MISE_TRUSTED_CONFIG_PATHS=/home/runner/work/shuiro/shuiro
2024-11-02T08:17:32.8210590Z Setting MISE_YES=1
2024-11-02T08:17:32.8211163Z Adding /home/runner/.local/share/mise/shims to PATH
2024-11-02T08:17:32.8214462Z ##[group]Running mise --version
2024-11-02T08:17:32.8231154Z [command]/home/runner/.local/share/mise/bin/mise --version
2024-11-02T08:17:32.8293756Z 2024.11.0 linux-x64 (eae29db 2024-11-01)
2024-11-02T08:17:32.8303868Z ##[endgroup]
2024-11-02T08:17:32.8304603Z ##[group]Running mise install 
2024-11-02T08:17:32.8316417Z [command]/home/runner/.local/share/mise/bin/mise install
2024-11-02T08:17:32.8415824Z [2mmise[0m all runtimes are installed
2024-11-02T08:17:32.8426081Z ##[endgroup]
2024-11-02T08:17:32.8641509Z ##[group]Run bun install --frozen-lockfile
2024-11-02T08:17:32.8641983Z [36;1mbun install --frozen-lockfile[0m
2024-11-02T08:17:32.8677514Z shell: /usr/bin/bash -e {0}
2024-11-02T08:17:32.8677836Z env:
2024-11-02T08:17:32.8678074Z   MISE_LOG_LEVEL: info
2024-11-02T08:17:32.8678642Z   MISE_TRUSTED_CONFIG_PATHS: /home/runner/work/shuiro/shuiro
2024-11-02T08:17:32.8679055Z   MISE_YES: 1
2024-11-02T08:17:32.8679291Z ##[endgroup]
2024-11-02T08:17:32.8927599Z bun install v1.1.34 (5e5e7c60)
2024-11-02T08:17:32.8956181Z Resolving dependencies
2024-11-02T08:17:33.6762805Z Resolved, downloaded and extracted [46]
2024-11-02T08:17:37.8627265Z Error: ENOENT: no such file or directory, stat '/home/runner/work/shuiro/shuiro/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node'
2024-11-02T08:17:37.8630213Z error: "prisma" exited with code 1
2024-11-02T08:17:37.8630904Z 12 | export default "unknown";
2024-11-02T08:17:37.8631489Z                     ^
2024-11-02T08:17:37.8632207Z ShellError: Failed with exit code 1
2024-11-02T08:17:37.8638889Z  info: {
2024-11-02T08:17:37.8639563Z   "exitCode": 1,
2024-11-02T08:17:37.8641755Z   "stderr": "Error: ENOENT: no such file or directory, stat '/home/runner/work/shuiro/shuiro/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node'\nerror: \"prisma\" exited with code 1\n",
2024-11-02T08:17:37.8643679Z   "stdout": ""
2024-11-02T08:17:37.8644045Z }
2024-11-02T08:17:37.8645040Z 
2024-11-02T08:17:37.8645668Z       at new ShellError (unknown:12:16)
2024-11-02T08:17:37.8649313Z       at new ShellPromise (unknown:72:16)
2024-11-02T08:17:37.8649982Z       at BunShell (unknown:187:35)
2024-11-02T08:17:37.8650844Z       at /home/runner/work/shuiro/shuiro/backend/src/bin/postinstall.ts:35:9
2024-11-02T08:17:37.8652224Z       at generatePrismaClient (/home/runner/work/shuiro/shuiro/backend/src/bin/postinstall.ts:34:30)
2024-11-02T08:17:37.8656583Z       at module code (/home/runner/work/shuiro/shuiro/backend/src/bin/postinstall.ts:40:7)
2024-11-02T08:17:37.8657594Z       at unknown:2:1
2024-11-02T08:17:37.8657886Z 
2024-11-02T08:17:37.8658073Z Bun v1.1.34 (Linux x64 baseline)
2024-11-02T08:17:37.8658588Z 
2024-11-02T08:17:37.8658977Z error: postinstall script from "backend" exited with 1
2024-11-02T08:17:37.9260685Z ##[error]Process completed with exit code 1.
2024-11-02T08:17:37.9388668Z Post job cleanup.
2024-11-02T08:17:38.0344556Z [command]/usr/bin/git version
2024-11-02T08:17:38.0388864Z git version 2.47.0
2024-11-02T08:17:38.0430766Z Temporarily overriding HOME='/home/runner/work/_temp/5ffab0e7-8ce3-4256-8bd8-c6bef6549e26' before making global git config changes
2024-11-02T08:17:38.0435686Z Adding repository directory to the temporary git global config as a safe directory
2024-11-02T08:17:38.0437224Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/shuiro/shuiro
2024-11-02T08:17:38.0470599Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-11-02T08:17:38.0502178Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-11-02T08:17:38.0733553Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-11-02T08:17:38.0754512Z http.https://github.com/.extraheader
2024-11-02T08:17:38.0767765Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-11-02T08:17:38.0799883Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-11-02T08:17:38.1225906Z Cleaning up orphan processes
```
</details>

**Comment by r4ai** [comment]
最近失敗しないので閉じます
